In [1]:
from lidar import Lidar_Segment
import pandas as pd
import numpy as np

In [28]:
lidar_pts = pd.read_csv('./data/lidar_converted.csv', delimiter=' ', header=None).values
Lidar = Lidar_Segment(lidar_pts, 40, 0.9)
Lidar.segment_data()

In [20]:
pt_output = '/home/bolunzhang/workspace/pcl_cloudViewer/plane1.pcd'
i = 8
np.savetxt(pt_output, Lidar.boards_pts_set[i])

In [32]:
print len(Lidar.boards_pts_set)
print [len(b) for b in Lidar.boards_pts_set]
sum = 0
for i in xrange(len(Lidar.boards_pts_set)):
    b_s = Lidar.boards_pts_set[i]
    sum += len(b_s)
print sum

37
[18608, 138, 151, 5338, 894, 1065, 185, 1185, 621, 757, 1694, 389, 230, 395, 451, 247, 280, 535, 260, 160, 269, 894, 299, 695, 296, 274, 231, 204, 194, 229, 158, 218, 151, 134, 329, 156, 320]
38634


In [31]:
n_pts = 0
lidar_file = open('/home/bolunzhang/workspace/pcl_cloudViewer/plane.pcd', 'w')
for i in xrange(len(Lidar.boards_pts_set)):
    b_s = Lidar.boards_pts_set[i]
    for j in xrange(len(b_s)):
        n_pts += 1
        lidar_file.write(str(b_s[j, 0]) + " " + str(b_s[j, 1]) + " " + str(b_s[j, 2]) + "\n")
print n_pts

38634


In [9]:
a = np.array([[1,2,3],[2,3,4]])
print(a)
a[:, 1: 2]

[[1 2 3]
 [2 3 4]]


array([[2],
       [3]])

In [23]:
from sklearn.neighbors import KDTree
import numpy as np
X = np.array([[-1,-1],[-2,-1],[-3,-2]])
kdt = KDTree(X, leaf_size=30, metric='euclidean')
(score, idx) = kdt.query([[-2,-0.5]], k=1, return_distance=True)
print(score[0][0])

0.5


In [6]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 0, -1]])
array3 = np.array([[1,2],[3,4]])
print(np.sign(array1.dot(array2.T))*array3)

[[-1 -2]
 [-3 -4]]


0
